# Generated by Django 5.1.7 on 2025-06-19 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=10, verbose_name='Action')),
                ('model', models.CharField(max_length=255, verbose_name='Model')),
                ('object_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Object ID')),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='Object')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Valid date')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Details')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Adminis')),
            ],
            options={
                'verbose_name': 'administrator_logs',
                'verbose_name_plural': 'Administrator Action Logs',
                'ordering': ('-created_at',),
            },
        ),
    ]
