# Generated by Django 5.1.7 on 2025-06-04 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='achievement',
            table='achievements',
        ),
        migrations.AlterModelTable(
            name='userachievement',
            table='user_achievements',
        ),
    ]
