# Generated by Django 5.1.7 on 2025-06-20 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_alter_achievement_table_alter_userachievement_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userachievement',
            name='achievement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='achievements.achievement'),
        ),
    ]
