# Generated by Django 5.1.7 on 2025-06-20 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0003_alter_userachievement_achievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userachievement',
            name='achievement',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='achievements.achievement'),
            preserve_default=False,
        ),
    ]
