# Generated by Django 5.1.7 on 2025-06-09 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank_accounts', '0015_remove_bankaccountinvitation_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTransfers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField(blank=True, default='Money Transfer')),
                ('frequency', models.CharField(choices=[('once', 'Однократно'), ('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('bi-weekly', 'Раз в две недели'), ('monthly', 'Ежемесячно'), ('annually', 'Ежегодно')], default='once', max_length=10)),
                ('next_occurrence_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_scheduled_transfers', to='bank_accounts.bankaccount')),
                ('sender_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_scheduled_transfers', to='bank_accounts.bankaccount')),
            ],
            options={
                'db_table': 'scheduled_transfers',
                'ordering': ['next_occurrence_date', 'start_date'],
            },
        ),
    ]
