# Generated by Django 5.1.7 on 2025-06-20 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduled_transfers', '0002_alter_scheduledtransfers_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtransfers',
            name='frequency',
            field=models.CharField(choices=[('once', 'Once'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('bi-weekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('annually', 'Annually')], default='once', max_length=10),
        ),
    ]
