# Generated by Django 5.1.7 on 2025-06-13 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank_accounts', '0016_bankaccount_balance_not_negative'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsAccount',
            fields=[
                ('bank_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='saving_account', serialize=False, to='bank_accounts.bankaccount')),
                ('goal_name', models.CharField(max_length=100)),
                ('goal_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('min_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_rate', models.DecimalField(decimal_places=3, editable=False, max_digits=5)),
                ('interest_period', models.CharField(choices=[('monthly', 'Ежемесячно'), ('yearly', 'Ежегодно')], default='monthly', max_length=10)),
                ('next_interest_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'savings_accounts',
            },
        ),
    ]
