# Generated by Django 5.1.7 on 2025-06-15 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings_accounts', '0002_savingsaccount_is_first_deposit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingsaccount',
            name='interest_period',
            field=models.CharField(choices=[('monthly', 'Ежемесячно'), ('yearly', 'Ежегодно')], error_messages={'invalid_choice': 'The interest accrual period must be "Monthly" or "Annually"'}, max_length=10),
        ),
    ]
