# Generated by Django 5.1.7 on 2025-06-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings_accounts', '0003_alter_savingsaccount_interest_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingsaccount',
            name='interest_period',
            field=models.CharField(choices=[('monthly', 'Ежемесячно'), ('yearly', 'Ежегодно')], max_length=10),
        ),
    ]
