# Generated by Django 5.1.7 on 2025-05-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='type',
            new_name='type_id',
        ),
        migrations.RemoveField(
            model_name='transactiontype',
            name='description',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
    ]
