# Generated by Django 5.1.7 on 2025-06-02 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transaction_amount_transaction_receiver_account_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransactionDetail',
        ),
    ]
