# Generated by Django 5.1.7 on 2025-06-02 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0007_rename_currencies_bankaccount_currency'),
        ('transactions', '0005_delete_transactiondetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receiver_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_transactions', to='bank_accounts.bankaccount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_transactions', to='bank_accounts.bankaccount'),
        ),
    ]
