# Generated by Django 5.1.7 on 2025-06-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_fill_transaction_amounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='converted_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Сумма в валюте получателя после конвертации', max_digits=15),
        ),
    ]
