# Generated by Django 5.1.7 on 2025-06-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_transaction_converted_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='converted_amount',
            field=models.DecimalField(decimal_places=2, help_text='Сумма в валюте получателя после конвертации', max_digits=15),
        ),
    ]
