# Generated by Django 5.1.7 on 2025-06-04 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_alter_transaction_converted_amount'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transaction',
            table='transactions',
        ),
        migrations.AlterModelTable(
            name='transactiontype',
            table='transaction_type',
        ),
    ]
