# Generated by Django 5.1.7 on 2025-06-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_alter_transaction_table_alter_transactiontype_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='converted_amount',
            field=models.DecimalField(decimal_places=2, help_text="Amount in recipient's currency after conversion", max_digits=15),  # noqa
        ),
    ]
