# Generated by Django 5.1.7 on 2025-05-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0003_alter_bankaccount_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='payment_system',
            field=models.CharField(choices=[('VISA', 'Visa'), ('MC', 'Mastercard'), ('MIR', 'Мир'), ('UPI', 'UnionPay')], default='MIR', max_length=4),
        ),
    ]
