# Generated by Django 5.1.7 on 2025-05-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0004_bankaccount_payment_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='payment_system',
            field=models.CharField(choices=[('VISA', 'Visa'), ('MC', 'Mastercard'), ('MIR', 'Мир'), ('UPI', 'UnionPay')], max_length=4),
        ),
    ]
