# Generated by Django 5.1.7 on 2025-05-31 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0005_alter_bankaccount_payment_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='currencies',
            field=models.CharField(choices=[('RUB', 'Ruble'), ('USD', 'Dollar'), ('EUR', 'Euro'), ('CNY', 'Yuan')], default='RUB', max_length=3),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='payment_system',
            field=models.CharField(choices=[('VISA', 'Visa'), ('MC', 'Mastercard'), ('MIR', 'Мир'), ('UPI', 'UnionPay')], default='MIR', max_length=4),
        ),
    ]
