# Generated by Django 5.1.7 on 2025-05-31 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0006_bankaccount_currencies_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccount',
            old_name='currencies',
            new_name='currency',
        ),
    ]
