# Generated by Django 5.1.7 on 2025-06-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0008_bankaccount_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(editable=False, max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='payment_system',
            field=models.CharField(choices=[('VISA', 'Visa'), ('MC', 'Mastercard'), ('MIR', 'Мир'), ('UPI', 'UnionPay'), ('JCB', 'Japan Credit Bureau')], default='MIR', max_length=4),
        ),
    ]
