# Generated by Django 5.1.7 on 2025-06-04 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0009_alter_bankaccount_account_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSystemCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_system', models.CharField(choices=[('VISA', 'Visa'), ('MC', 'Mastercard'), ('MIR', 'Мир'), ('UPI', 'UnionPay'), ('JCB', 'Japan Credit Bureau')], max_length=4, unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
