# Generated by Django 5.1.7 on 2025-06-04 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0010_paymentsystemcounter'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bankaccount',
            table='bank_accounts',
        ),
        migrations.AlterModelTable(
            name='paymentsystemcounter',
            table='payment_system_counter',
        ),
    ]
