# Generated by Django 5.1.7 on 2025-06-07 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0013_bankaccountinvitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccountinvitation',
            name='status',
        ),
    ]
