# Generated by Django 5.1.7 on 2025-06-07 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0014_remove_bankaccountinvitation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccountinvitation',
            name='updated_at',
        ),
    ]
