# Generated by Django 5.1.7 on 2025-06-09 06:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0015_remove_bankaccountinvitation_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='balance_not_negative'),
        ),
    ]
