# Generated by Django 5.1.7 on 2025-06-20 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0016_bankaccount_balance_not_negative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='payment_system',
            field=models.CharField(choices=[('VISA', 'Visa'), ('MC', 'Mastercard'), ('MIR', 'Mir'), ('UPI', 'UnionPay'), ('JCB', 'Japan Credit Bureau')], default='MIR', max_length=4),
        ),
        migrations.AlterField(
            model_name='paymentsystemcounter',
            name='payment_system',
            field=models.CharField(choices=[('VISA', 'Visa'), ('MC', 'Mastercard'), ('MIR', 'Mir'), ('UPI', 'UnionPay'), ('JCB', 'Japan Credit Bureau')], max_length=4, unique=True),
        ),
    ]
